name: Black

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Format all py files using black
      run: |
        black $(git ls-files '*.py') 
    - name: Commit changes
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        git stash -u
        black $(git ls-files '*.py')
        git stash pop
        git add .
        message="$(git log -1 --pretty=%B) Format Python code with Black"
        git diff-index --quiet HEAD || git commit -m "$message"
    - name: Push changes
      run: |
        git push origin master
